<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-B1VDJO44" ignored="0" name="BankingApp Test" tests="6" failures="3" timestamp="23 Dec 2019 06:59:52 GMT" time="102.909" errors="0">
  <testcase name="logintest" time="3.781" classname="com.inetbanking.TestCases.TC_logintest"/>
  <testcase name="loginDDT" time="14.946" classname="com.inetbanking.TestCases.TC_loginDDT_002"/>
  <testcase name="loginDDT" time="5.299" classname="com.inetbanking.TestCases.TC_loginDDT_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetbanking.TestCases.TC_loginDDT_002.loginDDT(TC_loginDDT_002.java:27)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="5.992" classname="com.inetbanking.TestCases.TC_loginDDT_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetbanking.TestCases.TC_loginDDT_002.loginDDT(TC_loginDDT_002.java:27)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="5.73" classname="com.inetbanking.TestCases.TC_loginDDT_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetbanking.TestCases.TC_loginDDT_002.loginDDT(TC_loginDDT_002.java:27)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="addnewcustomer" time="16.77" classname="com.inetbanking.TestCases.TC_addcustomertest"/>
</testsuite> <!-- BankingApp Test -->
